### ISSUE TITLE
Where is DaggerApplicationComponent?

### ISSUE THREAD

**Issue by ppamorim** [JorgeCastilloPrz/Dagger2Scopes#1]

**Comment by JorgeCastilloPrz** [comment]
That is one of the classes autogenerated by Dagger. Your IDE is not finding
them as those are not included in classpath until the app is compiled. You
might disable that Lint check to not see the red underline, or something. I
just ignore it :)

**Comment by ppamorim** [comment]
I've migrate from Dagger 1. This will take a time.

**Comment by ppamorim** [comment]
@JorgeCastilloPrz I've tried to build. But don't work.
What's the correct way to build this guy?

**Comment by ppamorim** [comment]
@JorgeCastilloPrz I've success on build to generate the DaggerApplicationComponent. But return this after import.

Error:(8, 32) error: cannot find symbol class DaggerApplicationComponent

**Comment by ppamorim** [comment]
@JorgeCastilloPrz  Please can you help me?

**Comment by JorgeCastilloPrz** [comment]
It is a lttle bit tricky sometimes to build the projects when they have red imports. I cannot tell you exactly what is happening about that, but get sure to clean, resync, and have a good component composition. If your components/modules are not ok it could fail like that too.

**Comment by ppamorim** [comment]
@JorgeCastilloPrz I just have cloned the project and return this:

```
UNEXPECTED TOP-LEVEL EXCEPTION:
...while parsing com/github/jorgecastilloprz/dagger2scopes/presentation/GameDetailsPresenterImpl.class

Error:Execution failed for task ':android:preDexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/java-8-oracle/bin/java'' finished with non-zero exit value 1
```

**Comment by JorgeCastilloPrz** [comment]
Never tried to compile an app with dagger or dagger 2 with Java8. Have you
tried to compile it using Java7 ?

**Comment by ppamorim** [comment]
@JorgeCastilloPrz I changed to JDK 7 amd64 and it works.

**Comment by JorgeCastilloPrz** [comment]
Ok!

**Comment by chnt-gomez** [comment]
I got fixed this problem adding comments to all uses of "DaggerApplicationComponent". Then clean project and rebuild.
Then remove comment lines and worked like a charm.

**Comment by kjoshi07** [comment]
It should be in Build-->generated if you have setedup Dagger 2 correctly, if not then make sure you added latest version and upgraded gradle version to support annotation in dependencies itself instead of adding apt.

**Comment by asanz8** [comment]
@chnt-gomez You saved my life!

**Comment by rizwan49** [comment]
> I got fixed this problem adding comments to all uses of "DaggerApplicationComponent". Then clean project and rebuild.
> Then remove comment lines and worked like a charm.

Thanks man, actually this way help us to find the redundancy in code and able to remove our mistake.

**Comment by berkkulaksiz** [comment]
> I got fixed this problem adding comments to all uses of "DaggerApplicationComponent". Then clean project and rebuild.
> Then remove comment lines and worked like a charm.

It works for me ! Thanks. By the way after that operation I got big smile on my face 🤣
