### ISSUE TITLE
Crash on excludeItemsFromTransitionIfLollipop

### ISSUE THREAD

**Issue by ppamorim** [JorgeCastilloPrz/Dagger2Scopes#2]
@TargetApi(Build.VERSION_CODES.LOLLIPOP) don't work properly.

I'll fix this.

Guykun says: "@TargetApi does not prevent any code from being run, it is merely for annotating code and preventing compiler errors for new APIs once you know you are only conditionally calling them."

**Comment by JorgeCastilloPrz** [comment]
To be honest, i never checked if the app was working correctly on pre lollipop devices as the main purpouse was to show the app structure :). I planned to check it later but i had not enough time for it yet. I will checkout your pr asap! 

Thanks.

**Comment by ppamorim** [comment]
I've fix it on #3, can you review?

**Comment by JorgeCastilloPrz** [comment]
Merged.
